Restrict pairing for literals/escaped char.
nkakouros-original/bash-autopairs pull request #2
Opened 2022-02-14 11:19 UTC by cevhyruz

This will exclude escaped registered pairs from auto-pairing. ideal for composing a regex

2022-02-14 11:34 UTC, nkakouros commented on autopairs.sh
> +  match="$(command tr -d '\\n' <<< "$match")"
I haven't gone through the whole commit, but a first comment is to not use `grep`, `tr` or anything that spawns a subprocess as this is expensive. Here you are calling `tr` (one subprocess) into a subshell (second process). Try to rewrite using bash internals only. 

Also, if you want to have things like `\"` excluded from matches, you can simply do sth like:

```
    num_of_char="${READLINE_LINE//\\\"}  # remove escaped quotes from the line
    num_of_char="${READLINE_LINE//[^$typed_char]/}"
    ...
```

I am not sure if `\\\"` is the correct number of backslashes, I haven't tested that, but you should get the point. In other words, you would only need a couple of lines to achieve that.

2022-02-14 14:04 UTC, cevhyruz commented on autopairs.sh
> +  match="$(command tr -d '\\n' <<< "$match")"
You're right. I was so focused on matching literals that I didn't realize it could be easier done with parameter expansion

2022-02-14 17:06 UTC, nkakouros commented on autopairs.sh
> +    if [[ "$(( ${#num_of_char} % 2 ))" -eq 1 ]]; then
Why not set `num_of_char` to hold the number of occurrences of the character already on line 19? This would be on par with the name of the variable and it would also make lines 24 and 28 a bit simpler.

2022-02-14 17:06 UTC, nkakouros commented on autopairs.sh
> +  num_of_char="${READLINE_LINE//\\${typed_char}}"
You don't need the brackets around the variable name.

```suggestion
  num_of_char="${READLINE_LINE//\\$typed_char}"
```

2022-02-14 17:06 UTC, nkakouros commented on autopairs.sh
> +    if [[ "$(( ${#num_of_char} % 2 ))" -eq 1 ]]; then
Actually is any of the changes other that lines 18 and 21-22 needed?

2022-02-15 03:44 UTC, cevhyruz commented on autopairs.sh
> +  num_of_char="${READLINE_LINE//\\${typed_char}}"
will remove it. I just thought that since there is another character included,  then variable must be in braces for readability

2022-02-15 03:46 UTC, cevhyruz commented on autopairs.sh
> +    if [[ "$(( ${#num_of_char} % 2 ))" -eq 1 ]]; then
> Actually is any of the changes other that lines 18 and 21-22 needed?
No actually. fixing this now.

2022-02-15 11:49 UTC, nkakouros requested changes

2022-02-15 11:49 UTC, nkakouros commented on autopairs.sh
> +  num_of_char="${READLINE_LINE//\\$typed_char}"
One more note, `num_of_char` is used only in one branch of the conditional. Moving it back there will avoid having this variable evaluated for cades it is not used.

2022-02-15 11:50 UTC, nkakouros commented
One last thing, could you update the README to mention that escaped characters are now supported?

2022-02-15 12:02 UTC, cevhyruz reviewed
Yeah sorry forgot about that.

2022-02-15 16:40 UTC, nkakouros commented
> Yeah sorry forgot about that.

No, thank you for devoting time on this.

I think this looks great! Do you think we need to worry about deleting as well?  I havemt tried the changes yet on my bash.

2022-02-15 21:34 UTC, nkakouros commented on README.md
> +Escaped character wont be auto paired to let you compose literals with ease.
```suggestion
Escaped characters won't be auto paired to let you compose literals with ease.
```

2022-02-15 21:34 UTC, nkakouros commented on README.md
> +try typing:
```suggestion
Try typing:
```

2022-02-15 21:34 UTC, nkakouros commented on README.md
> +```
```suggestion
```

```

2022-02-16 01:44 UTC, cevhyruz commented
>  Do you think we need to worry about deleting as well?

I think it's alright. unless we also would want to support deletion of escaped pairs which I think would defeat the purpose.

Also, there are occasions when you may want escaped pairs `\(\)` and/or a hanging opening/closing literals `\(\]` altogether.

2022-02-16 02:53 UTC, nkakouros approved these changes

2022-02-16 02:54 UTC, nkakouros commented
Thanks for spending time on this! It was sth that has been bothering me for some time too.

2022-02-16 02:54 UTC, merged